# GitHub Actions workflow to build and deploy a React app

name: React Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Use a stable version unless multiple versions are necessary

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set User Name
        run: git config --global user.name "Suraj Mate"

      - name: Set User Email
        run: git config --global user.email "matesuraj8@gmail.com"

      - name: Install dependencies
        run: npm i --force
        
      - name: Install github pages
        run: npm install --save gh-pages

      - name: Build React app
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d build -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git -u "github-actions-bot <github-actions[bot]@users.noreply.github.com>"
